If it couldn't allocate memory, don't attempt to write a bunch of values to the NULL pointer before returning it, but just pass the NULL along right away.
Resolves parfait warnings of the form:

Error: Null pointer dereference (CWE 476)
   Write to null pointer 'adapt'
        at line 248 of driver/xf86-video-s3/src/s3_video.c in function 'S3SetupImageVideoOverlay'.
          Function 'S3AllocAdaptor' may return constant 'NULL' at line 218, called at line 246.
          Null pointer introduced at line 218 in function 'S3AllocAdaptor'.

repeated for every line writing to the adapt pointer in the function.

[ This bug was found by the Parfait 0.4.2 bug checking tool.
  For more information see http://labs.oracle.com/projects/parfait/ ]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>